---
- hosts: manager
  become: true
  tasks:
    - name: Clone bitbucket repo
      git:
      repo: https://github.com/shubh11994/tower-example.git
      dest: /home/ubuntu/
      version: master
      
    - name: install cloudera manager
      shell: sh /home/ubuntu/cloudera.sh
      notify: cloudera manager up and running on host port 7810
